name: Build and Preview

on:
  pull_request_target:
    types:
      - edited
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build
        if: github.event.action != 'closed'
        run: |
          nix build

      - name: Copy build result
        run: |
          cp -rv $(readlink -f result) out

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./out/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: out/**